#use_frameworks!

target 'ZAColorChooseView_Example' do
  pod 'ZAColorChooseView', :path => '../'

  target 'ZAColorChooseView_Tests' do
    inherit! :search_paths


  pod 'Specta'
  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
